"""add_otps_table

Revision ID: 41e538d1df36
Revises: d9ba9831450e
Create Date: 2026-05-21 15:14:57.605460

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '41e538d1df36'
down_revision: Union[str, None] = 'd9ba9831450e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otps_email', 'otps', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otps_email', table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
