"""drop_general_roles

Revision ID: 47cbf23c17f4
Revises: de3fe6550b24
Create Date: 2026-05-19 14:57:03.462793

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '47cbf23c17f4'
down_revision: Union[str, None] = 'de3fe6550b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('user_general_roles')
    op.drop_table('player_general_roles')
    op.drop_table('general_roles')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_general_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('general_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['general_role_id'], ['general_roles.id'], name=op.f('player_general_roles_general_role_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('player_general_roles_player_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('player_general_roles_pkey')),
    sa.UniqueConstraint('player_id', 'general_role_id', name=op.f('player_general_roles_player_id_general_role_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_general_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('general_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['general_role_id'], ['general_roles.id'], name=op.f('user_general_roles_general_role_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_general_roles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_general_roles_pkey')),
    sa.UniqueConstraint('user_id', 'general_role_id', name=op.f('user_general_roles_user_id_general_role_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('general_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('general_roles_pkey')),
    sa.UniqueConstraint('name', name=op.f('general_roles_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
