"""add_thumbnail_url_to_videos

Revision ID: 8dd63c22ba16
Revises: 47cbf23c17f4
Create Date: 2026-05-20 00:04:45.815212

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '8dd63c22ba16'
down_revision: Union[str, None] = '47cbf23c17f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_url')
    # ### end Alembic commands ###
