"""unique_username

Revision ID: a6dcb4b158a6
Revises: 41e538d1df36
Create Date: 2026-05-21 15:54:54.874133

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'a6dcb4b158a6'
down_revision: Union[str, None] = '41e538d1df36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
