"""add_map_id_to_videos

Revision ID: d9ba9831450e
Revises: e7b3a1c2f4d9
Create Date: 2026-05-21 14:37:08.063100

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'd9ba9831450e'
down_revision: Union[str, None] = 'e7b3a1c2f4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('map_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'videos', 'maps', ['map_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'map_id')
    # ### end Alembic commands ###
